name: variant
version: 2.4.1
description: Roslin Variant Pipeline v2.4.1
root: /ifs/work/pi/roslin-pipelines
binding:
  core: bin
  data: resources
  output: outputs
  workspace: workspace
  extra:
    - /scratch
    - /ifs
dependencies:
  core:
    version:
      min: 2.0.5
      max: 2.0.5
  cmo:
    version: 1.9.10
    install-path: /ifs/work/pi/cmo_package_archive/
