name: variants
version: 2.3.0
description: Roslin Variant Pipeline v2.3.0
root: /ifs/work/pi/roslin-pipelines
binding:
  core: bin
  data: resources
  output: outputs
  workspace: workspace
  extra:
    - /scratch
    - /ifs
dependencies:
  core:
    version:
      min: 2.0.3
      max: 2.0.3
  cmo:
    version: 1.9.10
    install-path: /ifs/work/pi/roslin-cmo/1.9.10/cmo/
  toil:
    version: 3.15.1a1-MSK
    install-path: /ifs/work/pi/roslin-toil/3.15.1a1-MSK/toil/
  singularity:
    version: 2.5.1
    install-path: /opt/common/CentOS_6-dev/singularity/singularity-2.5.1/bin/singularity
test:
  root: /ifs/work/pi/roslin-test/
  tempDir: /scratch  
  runMode: singleMachine
  env:
    TOIL_LSF_ARGS: '-S 1 -We 0:59 -R select[internet]'
build:
  buildImages: true  
  installCore: true
  buildThreads: 4
  vagrantSize: 50GB