name: variant
version: 2.2.2
description: Roslin Variant Pipeline v2.2.2
root: /ifs/work/pi/roslin-pipelines
binding:
  core: bin
  data: resources
  output: outputs
  workspace: workspace
  extra:
    - /scratch
    - /ifs
dependencies:
  core:
    version:
      min: 2.0.3
      max: 2.0.3
  cmo:
    version: 1.9.8
    install-path: /ifs/work/pi/roslin-cmo/1.9.8/cmo/
  toil:
    version: 3.15.1a1-MSK
    install-path: /ifs/work/pi/roslin-toil/3.15.1a1-MSK/toil/
